### ISSUE TITLE
Recent "scancode" changes break NT keyboard

### ISSUE THREAD

**Issue by alexoughton** [MiSTer-devel/ao486_MiSTer#102]
The changes made in #96 have broken keyboard under Windows NT. Specifically this seems to be related to the change to the core itself, rather than the change to the BIOS.

Mister main version: 20220224
Core version: 22.02.24
BIOS: As-per most recent commit (5e0199a)
Behavior in DOS: Working fine. This is not the "corruption" issue people have been experiencing when not properly updating the BIOS.
Behavior in NT: Dead keyboard. Unable to CTRL+ALT+DEL to login. Caps-Lock non-responsive.

Mister main version: As above.
Core version: Revert back to 22.02.11
BIOS: Do not revert. Keep the new one with the updates.
Behavior in DOS: Corrupted (because I should have reverted the BIOS too if I wanted the keyboard to work...)
Behavior in NT: Working back to normal.

**Comment by sorgelig** [comment]
looks like NT requires scancode set 2 while dos uses Scancode set 1. By original idea it supposed to be switched by command to keyboard. Somehow it doesn't happen. I still don't have WinNT running on my MiSTer..

**Comment by sorgelig** [comment]
got it. thanks! will also check keyboard communication

**Comment by sorgelig** [comment]
ok, i know why it has wrong scan code set. I need to read more about PS2 keyboards and default scancode set.

**Comment by sorgelig** [comment]
this commit:
https://github.com/MiSTer-devel/ao486_MiSTer/commit/9eb5b85ee810c2d96a28287eb49db872c4e1b9ef
must be reverted.

**Comment by sorgelig** [comment]
fixed

**Comment by alexoughton** [comment]
Confirmed working under NT and DOS using newly released binaries.

**Comment by sorgelig** [comment]
https://wiki.osdev.org/%228042%22_PS/2_Controller#Translation

**Comment by spark2k06** [comment]
I see it, thank you. What I don't understand is this sentence: 

"Whenever this translation is enabled (and by default, it is) there is no way to reverse it in software."

How do you then disable it if necessary if by default it is enabled? by hardware?

**Comment by sorgelig** [comment]
they mean, you cannot translate code back. But you always can disable translation in config byte.
