### ISSUE TITLE
Nested findfirst/findnext calls may return incorrect data

### ISSUE THREAD

**Issue by p2mate** [MiSTer-devel/ao486_MiSTer#110]
Consider the following program:
```
/* Compile with Watcom C */

#include <dos.h>
#include <stdio.h>

static void check_findfirst(char *name)
{
        struct find_t fileinfo;
        unsigned err;

        err =  _dos_findfirst(name, _A_NORMAL, &fileinfo);
        while (err == 0) {
                printf("%s:%d %14s %10ld\n", __FILE__, __LINE__, fileinfo.name, fileinfo.size);
                err = _dos_findnext(&fileinfo);
        }
}
int main(int argc, char **argv)
{
        struct find_t fileinfo;
        unsigned err;

        err = _dos_findfirst("*.*", _A_NORMAL, &fileinfo);
        while (err == 0) {
                printf("%s:%d %14s %10ld\n", __FILE__, __LINE__, fileinfo.name, fileinfo.size);
                check_findfirst(fileinfo.name);
                err = _dos_findnext(&fileinfo);
        }

        return 0;
}

`````

running this on a HDD it results in:

```
testf1st.c:22    LICENSE.TXT      15371
testf1st.c:11    LICENSE.TXT      15371
testf1st.c:22       MAKEFILE       1196
testf1st.c:11       MAKEFILE       1196
testf1st.c:22      NANSI.ASM      34148
testf1st.c:11      NANSI.ASM      34148
testf1st.c:22      NANSI.DOC      28109
testf1st.c:11      NANSI.DOC      28109
testf1st.c:22       NANSI.MS      23582
testf1st.c:11       NANSI.MS      23582
testf1st.c:22      NANSI.SYS       3588
testf1st.c:11      NANSI.SYS       3588
testf1st.c:22    NANSI_D.ASM       1428
testf1st.c:11    NANSI_D.ASM       1428
testf1st.c:22    NANSI_F.ASM      17741
testf1st.c:11    NANSI_F.ASM      17741
testf1st.c:22    NANSI_I.ASM      11359
testf1st.c:11    NANSI_I.ASM      11359
testf1st.c:22    NANSI_P.ASM      10674
testf1st.c:11    NANSI_P.ASM      10674
testf1st.c:22          RAW.C       7198
testf1st.c:11          RAW.C       7198
testf1st.c:22          RAW.H       1279
testf1st.c:11          RAW.H       1279
testf1st.c:22      TOOLS.TXT        329
testf1st.c:11      TOOLS.TXT        329

```

The same directory on misterfs results in:
```
testf1st.c:22    LICENSE.TXT      15371
testf1st.c:11    LICENSE.TXT      15371
```

The reason is that misterfs only uses the path excluding the filename to generate the key which is used to address the context. Hence in this case both findfirst 'sessions' share the same context and both will stop after 1 because the second findfirst has only 1 matching file.

**Comment by user7182** [comment]
This explains the difficulty I've had trying to copy files from misterfs in FreeDOS using xcopy /e. It would only copy the first file of each folder recursively.

I can confirm making the key for the context before stripping the filename allows FreeDOS to copy all the files successfully. (This is in the [Main_MiSTer repository](https://github.com/MiSTer-devel/Main_MiSTer))

```
--- a/support/x86/x86_share.cpp
+++ b/support/x86/x86_share.cpp
@@ -960,8 +960,8 @@ static int process_request(void *reqres_buffer)
                        break;
                }
 
-               *flt++ = 0;
                key = add_lock(path);
+               *flt++ = 0;
 
                const char* full_path = getFullPath(path);
                DIR *d = opendir(full_path);

```

**Comment by sorgelig** [comment]
You can make PR if it fixes problem and doesn't produce other one.

**Comment by p2mate** [comment]
This indeed works, however I wonder if it wouldn't be better if the DOS side would pass a 16bit number to the 'server' code instead of using the search pattern. Then even nested identical search patterns would work. MisterFS was derived from a network filesystem implementation where this would not be possible because there can be multiple clients. However MisterFS has only 1 client. Disadvantage is that both misterfs.c and main_mister need to change for this.

**Comment by sorgelig** [comment]
if it will be more robust then it's not a problem to update both

**Comment by user7182** [comment]
@p2mate Passing a number from the client sounds like the right change. Are you going to look at making this change?

**Comment by p2mate** [comment]
yes. These should be the relevant PRs https://github.com/MiSTer-devel/Main_MiSTer/pull/569 and https://github.com/MiSTer-devel/ao486_MiSTer/pull/111

**Comment by user7182** [comment]
I just built both PR's and tried it in my FreeDOS environment and it worked great. I can copy files with xcopy no problem.
