### ISSUE TITLE
MisterFS broken

### ISSUE THREAD

**Issue by Lazarus404** [MiSTer-devel/ao486_MiSTer#114]
The MisterFS latest update (Mar 13) is broken. When launching, you cannot browse the files in Shared.  Instead, MSDOS simply says `File Not Found`.

Using the version before this works fine.

**Comment by sorgelig** [comment]
it should be coupled with latest Main.

**Comment by flynnsbit** [comment]
No only is it not broken, @user7182's changes have fixed the ability to not only edit files over on the misterfs drive but you can now run applications and games directly from there.  That has never been possible!  The only thing that doesn't work is Long File Name support through DOSLFNM.COM (See the Shareware pack VHD for examples)   This is awesome!!

**Comment by sorgelig** [comment]
i've tested MiSTerFS before today's release - everything works. The only problem slipped from me is backward compatibility. So both Main and MiSTerFS must be updated at the same time which is kind of tricky. Basically you need to use old Main and MiSTerFS to copy new MiSTerFS.exe, then update Main.
