### ISSUE TITLE
8259A PIC incompatibility issue

### ISSUE THREAD

**Issue by srmeister** [MiSTer-devel/ao486_MiSTer#122]
Hello,
once an IRQ input to the PIC is raised, setting mask on that IRQ doesn't clear the output "Interrupt_do" to the CPU, but it should.
But when the CPU reacts to the PIC in this situation, (interrupt acknowledge cycle) it will read no vector (zero vector) since the IRQ is masked.

**Comment by sorgelig** [comment]
can you provide testing code?

**Comment by srmeister** [comment]
`
cli
mov     al, 0FFh
out     21h, al
out     0A1h, al

sti
;interrupt will occur here if interrupt was raised before masking all Interrupts above

  `

**Comment by sorgelig** [comment]
try this build:
[ao486.zip](https://github.com/MiSTer-devel/ao486_MiSTer/files/9559749/ao486.zip)

**Comment by srmeister** [comment]
thank you, works fine now.
