### ISSUE TITLE
DOS. Games can't write to files (save game/save sound settings etc)

### ISSUE THREAD

**Issue by ritchiesinger** [MiSTer-devel/ao486_MiSTer#125]
Greetings!
I've create a VHD (using VirtualBox or Windows 10 inbox tool), install MS DOS 6.22 and required drivers on it. Everything looks fine.
After that I've copied some games on VHD and try to play. And I found that games can't write to files - can't save games (some games crashes with errors of open files or files are damaged, some games just freeze), can't save sound settings (setsound.exe etc) with similar error descriptions and crashes. Meanwhile I can create/edit/delete any file myself.
And these games works perfectly in dosbox without any errors.
Most likely this is not the ao486 problem, cause same errors I get while try to run the same VHD on VirtualBox machine, but I can't find solution in google (even can't find similar problem). Maybe someone here knows what I'm doing wrong?

**Comment by sorgelig** [comment]
Please go to MiSTer forum https://misterfpga.org to discuss about core usage/setup. It's not a core issue as writing to disk is a base feature.
