### ISSUE TITLE
Allow change of soundblaster IRQ?

### ISSUE THREAD

**Issue by rsn8887** [MiSTer-devel/ao486_MiSTer#14]
Some old games don't play well with the default soundblaster irq. For example, on real PC, Per.Oxyd is slow, 30 FPS, with default soundblaster irq 5. It shows the same behavior in dosbox. But it is fast, 60 FPS, when using irq 7.

Is it possible to make the irq setting configurable as a core option?

**Comment by sorgelig** [comment]
Well, it's possible in theory. Need to check if IRQ7 is occupied.

**Comment by Paradox** [comment]
there are a lot of jumper settings that need to be implemented, that you could change on real hardware.

**Comment by rsn8887** [comment]
I agree not a lot of jumpers are needed. But SB IRQ is a useful settings. Some few games like Per.Oxyd, even latest patched versions, run well only with IRQ 7 and show slowdowns or problems with IRQ 5. FWIW, the Dosbox emulator for Windows actually defaults to Soundblaster IRQ 7: https://github.com/jwilk-mirrors/dosbox/blob/b22a5212d1dd2240f27ea102e8eeae26bd551653/src/dosbox.cpp#L596

**Comment by wishusknight** [comment]
IRQ7 is used for LPT1 generally. I used to know exactly why IRQ5 was an issue for some titles and even knew how to correct it but for the life of me I can't remember now. If memory serves on my 386 it was corrected by disabling my floppy drive and com ports. But it has been 25 years... :(

**Comment by rsn8887** [comment]
This has already been implemented. Closing.
