### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Torinde** [MiSTer-devel/ao486_MiSTer#141]
Can [v586](https://opencores.org/projects/v586) be implemented on MiSTer?
Is it a better performing core?

**Comment by sorgelig** [comment]
I don't remember my login on opencores, but if i remember correct, it's netlist code, i.e. not maintainable, and with status beta with some unimplemented features. It's not new, so i definitely checked it.
Also, being Pentium code it definitely requires FPU implementation which is absent. Apps won't work on Pentium without FPU as it was native part of Pentium unlike i486 where it was optional.

x86 design is originally very complicated and i doubt it will be possible to run i486+ implementation faster on Cyclone V than it already implemented.
