### ISSUE TITLE
Support for VHD files using LRG mode

### ISSUE THREAD

**Issue by bikerspade** [MiSTer-devel/ao486_MiSTer#142]
I recently created two fixed-size 17MB VHD HDD disk images in 86Box:
Cylinders/Heads/Sectors (CHS): 697/3/17
Cylinders/Heads/Sectors (CHS): 1024/2/17
[VHDs.zip](https://github.com/MiSTer-devel/ao486_MiSTer/files/15016014/VHDs.zip)

![image](https://github.com/MiSTer-devel/ao486_MiSTer/assets/161802532/f1a1bf1e-95c2-4674-9ff8-5399c63af937)

Both disks have a single primary active partition that are formatted with an MS-DOS 6.22 system installed. Both are bootable in an 486-era machine in 86Box.

MiSTer is able to boot the 1024/2/17 disk, but is unable to boot the 697/3/17.

My 86Box machine BIOS detects the 1024/2/17 disk as LBA, and the 697/3/17 disk as LRG.
Could the ao486 core be updated to handle these?

### MiSTerFPGA:
![CHS_697_3_17](https://github.com/MiSTer-devel/ao486_MiSTer/assets/161802532/08e75cc4-6497-4e35-83ef-f49fffe44228)
![CHS_1024_2_17](https://github.com/MiSTer-devel/ao486_MiSTer/assets/161802532/0ed795cc-0782-4167-bfd7-8f3f5b7a114e)

### 86Box:
697/3/17:
![86Box_CHS_697_3_17](https://github.com/MiSTer-devel/ao486_MiSTer/assets/161802532/dc4b03c3-0b65-4a3e-9c0d-44228b1a29fe)
1024/2/17:
![86Box_CHS_1024_2_17](https://github.com/MiSTer-devel/ao486_MiSTer/assets/161802532/14fcabbd-7b46-409d-b73c-752f55df44d5)

**Comment by sorgelig** [comment]
MiSTer tries to autodetect the parameters. More different parameters it needs to detect means more chance to fail.
I suggest to (re)create VHD with parameters MiSTer can detect. That's the best solution.
