### ISSUE TITLE
Suggestion::Compile releases with Fitter Optimization = Aggressive Performance, Seed = 3141

### ISSUE THREAD

**Issue by YLFAndy** [MiSTer-devel/ao486_MiSTer#146]
I recompiled the core with the above options and it increased my performance a lot. (Attached). The core is also more stable when attempting MAX oc. I know that the fitter lotto will always produce slightly different results so it may not be replicable. 

Games tested with increased performance:
The Neverhood (Dramatically better)
Ultimate Doom (Better)
TekWar (Video was smoother, gameplay was dramatically better)
Blood/Duke/Redneck (Much better. High res runs like low res on current release core, low res runs fairly smooth)
RoadRash (marginally better)
Diablo (Dramatically better)

Games with no change:
Monkey Island 3

[ao486.zip](https://github.com/MiSTer-devel/ao486_MiSTer/files/15257138/ao486.zip)

**Comment by sorgelig** [comment]
Any change in code will change best SEED number.

**Comment by YLFAndy** [comment]
> Any change in code will change best SEED number.

I figured that was the case for seed. It's not calculable either, is it? You have to just seed build and run to find best? Which sounds awful.

**Comment by sorgelig** [comment]
You are right, there is no way to calculate a best seed. You only can build with different seeds and peek the best one.
