### ISSUE TITLE
20240524 release video out of sync

### ISSUE THREAD

**Issue by kold669** [MiSTer-devel/ao486_MiSTer#154]
New release has video completely out of sync with modelines enabled ( seems the video is above 35khz, max res of my setup multisync  crt monitor)
Previous one from April is working correctly

**Comment by sorgelig** [comment]
Are you talking about HDMI output?

**Comment by kold669** [comment]
Yes, i am using an hdmi to vga converter for analogue output.
When I use modelines ( direct video 0) the display is out of sync like the modelines are not recognized.
With the April release is working.
If i use direct video 1 , no display at all.

**Comment by sorgelig** [comment]
try this build:
[ao486_t1.zip](https://github.com/MiSTer-devel/ao486_MiSTer/files/15448329/ao486_t1.zip)

**Comment by kold669** [comment]
Just tried but no sync 😢

**Comment by sorgelig** [comment]
Make sure you don't use direct video as this core doesn't support it.

**Comment by sorgelig** [comment]
what `video_mode` do you use?
My test system runs 2048x1536 just fine.

**Comment by kold669** [comment]
This is the configurations I am using for the core. They worked until April update included.

[AO486]
direct_video=0 ; use the scaler
composite_sync=1
forced_scandoubler = 0
vga_scaler=0
vsync_adjust=2
vscale_mode=3
video_mode=1440,40,136,176,240,3,10,6,27000

alternate config 1:

[AO486]
direct_video=0
;video_mode=640,16,96,48,480,11,2,31,25170 ; 640x480@60hz
; video_mode=640,24,40,128,480,9,3,28,31500 ; 640x480@72hz
; video_mode=640,16,96,48,480,11,2,32,31500 ; 640x480@75hz
video_mode=640,8,58,78,240,1,3,18,12324 ; 320x240@60hz
;video_mode=720,24,65,71,240,4,3,15,13820 ; 720x240 60hz

alternate config 2:
[AO486]
direct_video=0
video_mode=640,16,96,48,480,11,2,31,25170 ; 640x480@60hz

**Comment by sorgelig** [comment]
if you replace core with april release, will it work again?

**Comment by sanstarr** [comment]
Same here. 
But i use a [Dell E1715S] Display.
Connected via VGA directly to Mister.
Resolution is 720x576, 50hz
All other cores working. 
release Of AO486 from april still working.
Error exists since last release…

Thanks for fixing.

BR

**Comment by kold669** [comment]
I confirm the core is working correctly with April release. It is the one I am using now waiting for a fix 🙏

**Comment by sorgelig** [comment]
Try this build:
[ao486_t2.zip](https://github.com/MiSTer-devel/ao486_MiSTer/files/15466554/ao486_t2.zip)

**Comment by sanstarr** [comment]
yep, its working! Thanks!
