### ISSUE TITLE
Graphical artifacts appearing as vertical lines

### ISSUE THREAD

**Issue by gingermike** [MiSTer-devel/ao486_MiSTer#161]
Updated to most recent build using the a0486 updater - now getting strange graphical artifacts on all games I've tested that appear as vertical lines:

![image](https://github.com/MiSTer-devel/ao486_MiSTer/assets/965703/0605cb6b-8e77-419d-a770-88ab489dc976)

Options are very vanilla - no graphical post processing applied

**Comment by sorgelig** [comment]
try this build:
[ao486_t1.zip](https://github.com/user-attachments/files/15858718/ao486_t1.zip)

**Comment by gingermike** [comment]
Thanks @sorgelig - that seems to have fixed it. Played a couple of minutes of Monkey Island 2 and Prince of Persia - no more issues!

**Comment by gtaylormb** [comment]
Lots of people reporting graphical issues since the last stable release on misterfpga.com and Discord. Probably due for a new release. People have been using the unstable nightly builds.
