### ISSUE TITLE
Strange columns of blinking pixels in almost every VGA game  

### ISSUE THREAD

**Issue by vanfanel** [MiSTer-devel/ao486_MiSTer#173]
@humply Starting with your recent changes, which fixed many games, I found that most VGA games show strange columns of blinking pixels.

For example, here's how it looks on Prince of Persia 2, but almost any game will do, it's more visible on some than others:

![photo_2024-12-20_00-27-32](https://github.com/user-attachments/assets/4e8cf018-ff92-463b-9d83-a351bb6bb6f8)

These are not shown when using the MiSTer capture via Win+PrintScreen.
Using or not using a video processing preset does not make any difference.
Changing core video options doesn't make any difference either.

Since you're on a row fixing things on this core (many, many thanks!!), could you please take a look?

**Comment by humply** [comment]
Thank you, I'm glad to hear you're happy with the bugfixes.

If you see this with all games, this issue is probably caused by a bad build, which can occasionally happen. I did try to reduce VGA timing violations. Please try to rebuild the core with maybe a different seed and see it that resolves the issue. I just tested Prince of Persia 2 and did not see the mentioned graphical issue on my end.

**Comment by vanfanel** [comment]
@humply I have tried to build it myself (I was using the version auto-generated on the MiSTer unstable nightlies here: https://github.com/MiSTer-unstable-nightlies/ao486_MiSTer/releases/download/unstable-builds/ao486_unstable_20241219_0529c9.rbf), but I get those errors on Quartus Prime Lite 21.1.0:
```

Error (12006): Node instance "pll_hdmi" instantiates undefined entity "pll_hdmi". Ensure that required library paths are specified correctly, define the specified entity, or change the instantiation. If this entity represents Intel FPGA or third-party IP, generate the synthesis files for the IP.
Error (12006): Node instance "pll_cfg_hdmi" instantiates undefined entity "pll_cfg_hdmi". Ensure that required library paths are specified correctly, define the specified entity, or change the instantiation. If this entity represents Intel FPGA or third-party IP, generate the synthesis files for the IP.
Error (12006): Node instance "pll_audio" instantiates undefined entity "pll_audio". Ensure that required library paths are specified correctly, define the specified entity, or change the instantiation. If this entity represents Intel FPGA or third-party IP, generate the synthesis files for the IP.
Error (12006): Node instance "pll" instantiates undefined entity "pll". Ensure that required library paths are specified correctly, define the specified entity, or change the instantiation. If this entity represents Intel FPGA or third-party IP, generate the synthesis files for the IP.
Error (12006): Node instance "pll_cfg" instantiates undefined entity "pll_cfg". Ensure that required library paths are specified correctly, define the specified entity, or change the instantiation. If this entity represents Intel FPGA or third-party IP, generate the synthesis files for the IP.
Info (144001): Generated suppressed messages file /home/manuel/src/ao486_MiSTer/output_files/ao486.map.smsg
Error: Quartus Prime Analysis & Synthesis was unsuccessful. 5 errors, 16 warnings
	Error: Peak virtual memory: 2080 megabytes
	Error: Processing ended: Fri Dec 20 07:18:58 2024
	Error: Elapsed time: 00:00:31
	Error: Total CPU time (on all processors): 00:00:39
Error (293001): Quartus Prime Full Compilation was unsuccessful. 7 errors, 17 warnings

```

Can you please share your build?
Any idea about those errors when building?

**Comment by vanfanel** [comment]
@humply More news on this.
I was able to build the project successfully by using Quartus Lite 17.0.0 (I had to manually install libpng12 on my system via dpkg, because current Debian uses libpng16, but oh well...)

The resulting build does NOT show those strange columns of blinking pixels, so the nightly unstable version is indeed a "bad build" as you predicted :)

This is my build for everybody to try:
[ao486.rbf.zip](https://github.com/user-attachments/files/18210063/ao486.rbf.zip)

**Comment by humply** [comment]
Thank you for verifying the bad build. I'm happy to hear you have a good build now for testing. It seems the unstable nightly build is appropriately named unstable. 😄

As you already noticed, you should indeed use Quartus 17.0 (e.g. 17.0.2) to build this core. This is also mentioned in the readme.

**Comment by vanfanel** [comment]
> Thank you for verifying the bad build. I'm happy to hear you have a good build now for testing. It seems the unstable nightly build is appropriately named unstable. 😄
> 
> As you already noticed, you should indeed use Quartus 17.0 (e.g. 17.0.2) to build this core. This is also mentioned in the readme.

Yep, I should have paid close attention to the readme... :)
Well, it's good what ends good!

**Comment by gtaylormb** [comment]
Instead of dealing with installing dependencies, try using a Docker image for Quartus: https://github.com/raetro/sdk-docker-fpga (there is a specific MiSTer version for Quartus, 17.0.2). Very good use case for Docker here; old programs with deps that newer OS's no longer support.

Since I've been working with the core it has never been even close to meeting timing (we're essentially overclocking the FPGA), so graphical issues can arise from build to build. This happened to me several times. I have not built yet with @humply 's incoming changes, but just wanted to highlight this was a problem before as well.

FPGA timing is a dark art, similar to overclocking a CPU. If the timing constraints are correct and the static timing analysis says you're not meeting them, all bets are off.

**Comment by humply** [comment]
The core indeed still has timing issues (e.g. l2cache). I'm still a novice when it comes to FPGA programming and it was indeed tricky to add some pipeline stages at the bottlenecks in the VGA implementation. After that I did see less VGA timing issues, but bad builds can still happen.

**Comment by sorgelig** [comment]
This core is known to have timing problems. Cyclone V is too slow for this core.
So usually after build i do some tests to see if there are glitches or not. If yes, then i build another version, and so on..

**Comment by humply** [comment]
Oh, so maybe fixing all timing issues is actually not even feasible on Cyclone V (or not worth the effort)? Checking for a bad build has become second nature to me! I've had to build a lot of cores while working on the VGA. 😃

**Comment by vanfanel** [comment]
> This core is known to have timing problems. Cyclone V is too slow for this core. So usually after build i do some tests to see if there are glitches or not. If yes, then i build another version, and so on..

I can see the core might be too fast for the DE-10 for implementing a 486-DX33, but what about making it a 386-class machine as maximum? My opinion is that it's better to have a correct 386 than a glitchy 486.
