### ISSUE TITLE
Feature request: 4.77 Mhz 

### ISSUE THREAD

**Issue by PhantombrainM** [MiSTer-devel/ao486_MiSTer#18]
Hi there,

since you are currently actively developing the ao486 right now, can you implement a "Turbo Button" for very old games which reduce the speed to 4.77Mhz?

That would be usefull. Thank you.

**Comment by sorgelig** [comment]
CPU is not cycle accurate, so it's impossible to make true 4.77 as some instruction will work faster and some will be slower.

**Comment by sorgelig** [comment]
Fox XT emulation another core should be written/ported based on i8086 CPU.
ao486 probably won't go bellow 15MHz because of some limitations.

**Comment by PhantombrainM** [comment]
Makes sense. I can confirm and remember old (newer) computers were too fast even with turbo disabled for some very old games. Thank you for checking recent core for possibilities (<15 Mhz unstable/CPU timings). Closed.

**Comment by Paradox** [comment]
I'm wondering if any care is being taken to ensure someone could create drop in CPUs (and, easily adjust other, necessary options) to make clones of this core that would contain the instruction set, etc. for other systems, such as the mentioned 8086, as well as 8088, 80286, 80386, maybe even, pentium (although, it may never reach full speeds) possibly even an openx86 https://www.reddit.com/r/linux/comments/9mlh3a/an_opensource_x86_processor/

Let's be clear, I'm not demanding anyone do anything, but, I'm just curious, how hard it would be to do this kind of thing.

**Comment by sorgelig** [comment]
For discussion use MiSTer forum.
Please keep github clean from discussions. Github is for bug tracking only!

**Comment by Paradox** [comment]
Sorry, will do.
