### ISSUE TITLE
Frix

### ISSUE THREAD

**Issue by bonnefoi** [MiSTer-devel/ao486_MiSTer#2]
Hello,

Do you have tried porting Frix over MiSTer ?
It is a development of ao486 without the Altera Nios II processor 
http://www.arch.cs.titech.ac.jp/a/Frix/

**Comment by sorgelig** [comment]
MiSTer's ao486 doesn't use NIOS II processor.

**Comment by bonnefoi** [comment]
It's listed on the ressources.

**Comment by sorgelig** [comment]
No idea what you are talking about.

**Comment by bonnefoi** [comment]
NIOS2 controller

The ao486 SoC uses a Altera NIOS2 processor

**Comment by sorgelig** [comment]
Everything bellow "Original ao486 Readme" has very little relation to MiSTer version.

**Comment by bonnefoi** [comment]
Ok. Thanks for the correction.
