### ISSUE TITLE
Sound/video goes out of sync in the Future Crew - Second Reality

### ISSUE THREAD

**Issue by ctafield** [MiSTer-devel/ao486_MiSTer#23]
Second Reality by Future Crew seems to have weird timing issues that pushes the sound/video out of sync. Also some sections flat out do not render.

Demo can be obtained here, along with a video of running correctly https://archive.org/details/FutureCrewSecondReality

Appreciate that demos tend to push the envelope with regards to hardware, but thought it worth reporting none the less (given that all I use this core is for demos!)

**Comment by sorgelig** [comment]
This core is NOT for demos and most likely will never be.
So, forget about non-working demos.
