### ISSUE TITLE
Joystick broken in X-Wing/TIE FIghter DOS floppy editions

### ISSUE THREAD

**Issue by rhester72** [MiSTer-devel/ao486_MiSTer#27]
Worked in prior public release (before the first cache changes) - joystick not recognized at all now (even during manual calibration)

**Comment by rhester72** [comment]
I forgot to mention that this behavior is identical with 2-button, 4-button, and Gravis configurations.

**Comment by rsn8887** [comment]
If I connect two controllers (pressing a on both to activate controller 1 and then 2), then I can skip steps using controller buttons on controller 2, but the joystick directions still don’t seem to work in the game.

**Comment by rhester72** [comment]
Fixed and closing - thank you VERY much!
