### ISSUE TITLE
Windows 98 freezes on boot

### ISSUE THREAD

**Issue by Kreeblah** [MiSTer-devel/ao486_MiSTer#31]
I've tried Windows 98 first edition and second edition, and both freeze on boot.  The installation finishes, and the system begins booting into the OS (with the moving colored strip on the bottom), but during that process, the moving strip eventually freezes and the OS stops responding to input.

If I press escape to show the text behind the boot graphic before it hits that point, it freezes on a blinking cursor instead, with no error message.  However, if I wait until it freezes to press escape, it stays on the frozen boot graphic.

This happens on ao486 20200814 and 20200816, with the new boot0.rom and ET4000 boot1.rom.  Both versions of the OS were installed by first booting from a boot floppy in VirtualBox to copy the setup files from the CD to the hard drive, and then transferring the image to MiSTer, where it was installed with:

setup /is /nm

**Comment by NML32** [comment]
@EgillSkallagrimsson Thank you, your suggestion worked for me.

**Comment by sorgelig** [comment]
Please don't post such bugs in github! It's not forum. "Windows hangs" may come from thousands issues. Useless bug report!
