### ISSUE TITLE
MIDI/MUNT operation not working properly.  

### ISSUE THREAD

**Issue by Knimrod** [MiSTer-devel/ao486_MiSTer#35]
Tested with several Sierra games previously working using MT-32 emulation..  With the new AO486 core, the only sound after game initialization is a faint bass droning sound with perhaps a few familiar notes being played intermittently.

**Comment by sorgelig** [comment]
New version of core may be too fast for some old games. Try to reduce CPU clock and/or disable cache for those games.
And before that make sure you configured MIDI output correctly on known to work games like DOOM or Tie Fighter.

**Comment by Knimrod** [comment]
Negative.  Trying different clock speeds, cache on or off doesn't seem to make any difference.  I still get what sounds like very sporadic random notes played.  Game play appears to be fine.  Only MIDI/MUNT appears to not work properly on this core.

Before this update, Game and MIDI seemed to work nominally with only an occasional music glitch that I attributed to the slow processor speed.

**Comment by Kitrinx** [comment]
Sierra games in particular are sensitive to clock speeds. This is easily observable in things like Quest for Glory1 vga or Quest for glory 3. You can use softmpu with these games which has fixes for high speeds, or run at 15-30mhz to fix the problem.

**Comment by Knimrod** [comment]
Thanks.  While my testing is limited to a few versions of Space Quest, Police Quest and Leisure Suit Larry, I cannot get any to work with the new AO486 MUNT at any clock speed.  Not at 15MHz, not at 30MHz.  It tries at any clock speed but no joy...just a droning sound occasionally and a few sporadic notes here and there.  The synth sounds are just not right. It may be the MIDI sysex messages not being transmitted/received correctly?  All were previously working with older AO486 core albeit just a little marginal with a sound glitch here and there.

**Comment by Kitrinx** [comment]
the MUNT that runs ON mister can't handle more than one or two channels. The HPS's processor is just too slow. UDP midi works great though.

**Comment by Knimrod** [comment]
It appears that the latest AO486 release has sorted the MIDI/MUNT problem I was having.  It's working again but still with the occasional glitches I had at the start.  I've always assumed the glitches were the result of the slow speed of the HPS processor and it is what it is.  It useable as is again so I'll close this issue.
