### ISSUE TITLE
WIN+F12 doesn't work on Release 20200922

### ISSUE THREAD

**Issue by fiorefr73** [MiSTer-devel/ao486_MiSTer#44]
The Win+F12 combination doesn't work anymore for me on version Release 20200922.
It works ok with previous versions.

Thanks
Francesco

**Comment by sorgelig** [comment]
Cannot confirm. It works fine here.
Just restart MiSTer or power cycle it. Make sure you've updated Main as well.

**Comment by fiorefr73** [comment]
Hi sorgelig, thanks!
I connected the MiSTer to the network and launched an update. Now WIN+F12 works as expected.
Sorry for inconvenience.

Regards
Francesco
