### ISSUE TITLE
AO486 CD Mounting using BIN/CUE or IMG/CUE bug and workaround found.

### ISSUE THREAD

**Issue by flynnsbit** [MiSTer-devel/ao486_MiSTer#46]
Some CD's were not mounting when a combination of either BIN/CUE or IMG/CUE was used for mounting the CD.  You would get a general failure when trying to use the drive mounted.  One work around was to rename either the .bin or the .img file to a .ISO file and mount that file instead.  That worked.  
I found another way that I hope gives some better insights into the bug.

If you have a CUE file that does not have an audio track with it, the mounting seems to fail.  If you add a dummy audio track then that cd will mount successfully and you can read it from within AO486:

Example:

Change this CUE sheet:
```
FILE "swtiecd.bin" BINARY
   TRACK 01 MODE1/2352
      INDEX 01 00:00:00
```
and now add a dummy audio track below it
```
FILE "swtiecd.bin" BINARY
   TRACK 01 MODE1/2352
      INDEX 01 00:00:00
   TRACK 02 AUDIO
      INDEX 01 00:00:01
```
Now re-mount the .cue file and the CD will load and read.

**Comment by sorgelig** [comment]
thanks for exploring the bug and give a useful additional info!

**Comment by sorgelig** [comment]
i've pushed the fix.

**Comment by flynnsbit** [comment]
Awesome.  Thank you so much!

**Comment by flynnsbit** [comment]
Leaving open until the official Main build comes out but everything looks good on this change.  I haven't run into a single img/bin with cue combo that doesn't work now.  I tested about 200 games.
