### ISSUE TITLE
Feature Request: Mapper command to allow for on the fly per game Joystick button to keyboard mapping

### ISSUE THREAD

**Issue by flynnsbit** [MiSTer-devel/ao486_MiSTer#47]
Similar to sysctl and imgset control from AO486, request is to allow for passing a config for joystick button to keyboard mapping on the fly.  Example file attached that is used with DOSBox but could be any structure as long as a dos command can pass mapping per button to keyboard keys.  This does not need to be saved as it will be passed by the DOS Launcher scripts for each game and can reset on core reset/restart.  As long as a command can be run, I can integrate the command into the launch script for all dos games.

Allowing for sending either commands or a file that sets the "Button/Key remap for game" option in the core would work perfectly.
![image](https://user-images.githubusercontent.com/32404856/98318188-b6af3c80-1fa3-11eb-9634-4b043f5aa121.png)

Example:
[mapper.txt](https://github.com/MiSTer-devel/ao486_MiSTer/files/5498397/mapper.txt)

If we had this type of command we could:
On boot/on launch of Total DOS Launcher for AO486:
Send command to map joystick buttons to U/D/L/R PgUP/PgDwn/ Enter and esc to allow for full Launcher control with a Joystick.

Once a game is selected a launch script for that game is run (1_START.BAT).  Inside the 1_START.BAT batch:
Change Joystick to Keyboard map to assign the appropriate keyboard keys to a joystick button.  
This will allow for most dos games to be controlled using a joystick even if they do not support joystick commands.

Saving this mapping is not necessary as the launcher can reset it or it can be run on a per game basis. (similar to imgset)

**Comment by sorgelig** [comment]
Besides very rare games really requiring analog stick (flight or racing simulators) the wast majority are written to control from keyboard. It's a classic PC, not console. 
So original intent is actually wrong. The main controller for PC is keyboard, not joystick. Attempt to change it will only add mess. Joysticks have different key codes by the way. Once you change the joystick - you have to rewrite all your mappers.
Games being written for keyboard don't limit the amount of keys used, so it will require joysticks with many buttons.
Overall i don't see such thing as useful. At the end, it's not a problem to quickly map the gamepad for current game in available (mentioned above) option.

**Comment by flynnsbit** [comment]
Good point on the Launcher.  I can do that instead.
