### ISSUE TITLE
Please, please add "Backspace to unmount" text hint somewhere to the IDE 0-0, IDE 0-1, etc screens.

### ISSUE THREAD

**Issue by flynnsbit** [MiSTer-devel/ao486_MiSTer#50]
No one seems to be able to read the FAQ.  It would be SO helpful from a support perspective to add a hint on the "SELECT" VHD/CD screens that just says something like *Backspace key to unmount"

**Comment by flynnsbit** [comment]
Thank you!!!!

**Comment by kblood** [comment]
Ahh very nice. I had been meaning to make an issue about this as well. It just makes sense to have this explained in the UI itself. The FAQ should mainly be needed for the more advanced stuff I think although this should also be in it.
