### ISSUE TITLE
MidiLink Remote/TCP not working in ao486_20210103

### ISSUE THREAD

**Issue by desaster** [MiSTer-devel/ao486_MiSTer#53]
Hi!

I'm trying to use the Remote/TCP feature of MidiLink with ao486.

It seems that the latest version broke something, since I'm unable to get any communication with MIDI/Remote/TCP. Console and PPP works fine.

It took me a while to figure out how to configure it properly, since the GUI doesn't allow selecting any baudrates other than 31250:

![image](https://user-images.githubusercontent.com/631441/103648407-82390c00-4f65-11eb-983e-e2949cde96fd.png)

However, I figured out that the default TCP baudrate is actually 115200, and the serial port is initialized correctly:

```
Setting /dev/ttyS1 to 115200 baud.
```

After a bit of head scratching, I downgraded ao486 to 20201106, and the TCP connection simply started working.

To illustrate how I'm testing this, here's screenshots of bananacom in action:

![ao486_20201106-midilink-tcp](https://user-images.githubusercontent.com/631441/103647688-608b5500-4f64-11eb-9e6b-cd2e7654381e.png)
**ao486_20201106 (previous release)**

![ao486_20210103-midilink-tcp](https://user-images.githubusercontent.com/631441/103647693-62551880-4f64-11eb-9d13-79d4b482e5e5.png)
**ao486_20210103 (current release)**

[ao486_20210103-midilink-tcp.log](https://github.com/MiSTer-devel/ao486_MiSTer/files/5770245/ao486_20210103-midilink-tcp.log)

**Comment by sorgelig** [comment]
Never saw TCP connection over MPU401.

**Comment by desaster** [comment]
To clarify: I'm using MidiLink/TCP as a modem for connecting to BBS.

Quote from https://github.com/MiSTer-devel/MidiLink_MiSTer:

_MidiLink : TCP The TCP option works like a WiFi232 adapter supporting a small subset of the Hayes "AT" command set and some additional stuff_

**Comment by sorgelig** [comment]
I think UART modes must be revised. Currently when MIDI mode is selected, linux UART is connected to MPU401 and there is no way to use it.
Probably some DialUp mode should be introduced in addition to PPP/Console/MIDI.

**Comment by desaster** [comment]
I've just checked out the latest release of ao486 for MiSTer, and modem connectivity with MidiLink seems to be working again.

"Modem" is now an extra option in the UART settings, which is very nice. UART selection also works.

Thanks!
