### ISSUE TITLE
MisterFS broken for all memory configuration with MiSTer_20210207 build

### ISSUE THREAD

**Issue by flynnsbit** [MiSTer-devel/ao486_MiSTer#58]
Tested Misterfs on ao486 with  MiSTer_20210207 and once you try to run DIR on the shared folder it will lock up the core and the menu.  hard physical reset or SSH in and reboot are the only solutions. 
MiSTer_20210109 verified as working with the same configuration and ao486 core, and setup.

Multiple reports of misterfs locking up from community now.

**Comment by sorgelig** [comment]
got it.. will fix soon

**Comment by flynnsbit** [comment]
Confirmed fixed in Release 20210222.  Thank you Sorg.
