### ISSUE TITLE
Unable to open zip files

### ISSUE THREAD

**Issue by kaloun34** [MiSTer-devel/ao486_MiSTer#60]
Hello

I don't know if it has already worked or if it's after an update. Cannot open my IMG files archived in a zip
I just tried with an older version of the main MiSTER and it works.

**Comment by sorgelig** [comment]
MiSTer supports simple file loading from zip like ROMs. It doesn't support file mounting from zip and never supported before. ZIP has very slow positioning and thus gives different kinds of issues.
I don't know what "older version" you are talking about.

**Comment by kaloun34** [comment]
For example, with the main MiSTer_20201213, I can mount my .img file from my floppy.zip file

**Comment by sorgelig** [comment]
It was a side effect (incomplete check). Mounting files from zip is not supposed to be supported. ZIP is not suitable container for random access. Such thing may work ok on PC with large memory and temporary files cached by OS. MiSTer is embedded system without such resources, so if it opens zip then it accesses the zip with every sector of image requested from core with very slow positioning for every sector in ZIP. It may affect not only disk access performance but the whole I/O for core including keyboard, joystick etc.. 

So, nope.

**Comment by kaloun34** [comment]
Thank you for your reply and for your work on the MiSTer.
