### ISSUE TITLE
sysctl.exe usage does not match documentation

### ISSUE THREAD

**Issue by alexoughton** [MiSTer-devel/ao486_MiSTer#65]
Hello,

I am looking at the documentation here: https://github.com/MiSTer-devel/ao486_MiSTer#core-speed-and-options-and-drivers
I am looking at the copy of sysctl.exe here: https://github.com/MiSTer-devel/ao486_MiSTer/tree/master/releases/drv

The documentation states usage of: SYSCTL SYS/MENU 90Mhz/56Mhz/15Mhz L1+/L1- L2+/L2-

However, I cannot get sysctl.exe to work with this syntax. I have found that the sysctl.exe at the above link works with hex syntax, i.e. sysctl.exe 82 or sysctl.exe 0. Looking in sysctl.c in the repo, it does look like it will only accept hex syntax.

On the forums I found: https://misterfpga.org/viewtopic.php?p=8730&sid=8ba8470457be790dbca4247af131d91f#p8730

There, bbond007 has shared their custom version of sysctl.com which uses the syntax found in the documentation linked above. Should the documentation show hex-style usage, or should sysctl.exe and sysctl.c in the repo have been updated?

Thanks in advance,

Alex Oughton

**Comment by sorgelig** [comment]
i've updated sysctl with new syntax from bbond007
