### ISSUE TITLE
Minor documentation issue with README

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/ao486_MiSTer#68]
> 486DX33 performance (no-FPU).

Actually, the CPU model without an FPU would be the SX, not the DX.

**Comment by sorgelig** [comment]
SX/DX has no direct relation to FPU.
It's about bus clock multiplier. DX means bus clock is doubled inside the CPU.

**Comment by c0d3h4x0r** [comment]
I've never heard that claim before in my life.  Ask anyone who grew up with PCs in the 1990s what the difference is, and they'll say that DX has an FPU whereas SX does not.  Even [Wikipedia](https://en.wikipedia.org/wiki/Intel_80486) says so.

If you are technically correct, then a clearer explanation in the README would help, because what it is saying does not align or agree with the common understanding.

**Comment by wishusknight** [comment]
> 
> 
> SX/DX has no direct relation to FPU.
> It's about bus clock multiplier. DX means bus clock is doubled inside the CPU.

Nup.. You are thinking of the 386 where SX had 16 bit external bus and the DX had a 32 bit external bus.. For the 486 the SX was no FPU and the DX had an FPU... For clock doubled 486s they were designated DX/2 or SX/2.. And clock tripled were designated DX/4 or SX/4 But I don't think intel ever released an SX/4. 

https://en.wikipedia.org/wiki/Intel_80486SX
"Intel's i486SX was a modified Intel 486DX microprocessor with its floating-point unit (FPU) disabled. It was intended as a lower-cost CPU for use in low-end systems. Computer manufacturers that used these processors include Packard Bell, Compaq, ZEOS and IBM. "

**Comment by cursedverses** [comment]
For clarification (using wikichip.org)

SX=No FPU
DX=With FPU
DX2=DX, Clock Doubled
DX4=DX, Clock Quadrupled

**Comment by wishusknight** [comment]
> 
> 
> For clarification (using wikichip.org)
> 
> SX=No FPU
> DX=With FPU
> DX2=DX, Clock Doubled
> DX4=DX, Clock Quadrupled

DX4 is clock tripled.... not quadrupled. Only Quad clocked 486 was amd's X5.....

**Comment by cursedverses** [comment]
Ah, apologies. I would've swore my old DX4/100 was 25MHz clock. It was 33MHz. I've fixed my comment. Thanks!
