### ISSUE TITLE
IMGSET failing after Release 20210630. 8fd0985

### ISSUE THREAD

**Issue by flynnsbit** [MiSTer-devel/ao486_MiSTer#73]
imgset for cd mounting is failing after the latest update.  I've attached a video for reference.  manually mounting CD's still functions, only fails when using the imgset command.

[2021-07-01 12-23-10.zip](https://github.com/MiSTer-devel/ao486_MiSTer/files/6749850/2021-07-01.12-23-10.zip)

**Comment by sorgelig** [comment]
try this build:
[MiSTer.zip](https://github.com/MiSTer-devel/ao486_MiSTer/files/6750033/MiSTer.zip)

**Comment by flynnsbit** [comment]
Same.  one more video, tried without quotes as well just to make sure that wasn't what was throwing it off.  
[2021-07-01 14-44-59.zip](https://github.com/MiSTer-devel/ao486_MiSTer/files/6750453/2021-07-01.14-44-59.zip)

**Comment by flynnsbit** [comment]
> Same. one more video, tried without quotes as well just to make sure that wasn't what was throwing it off.
> [2021-07-01 14-44-59.zip](https://github.com/MiSTer-devel/ao486_MiSTer/files/6750453/2021-07-01.14-44-59.zip)
> I missed the underscore in the video but I did test mi1 again, plus descent.

Hold on, let me test some more.

**Comment by flynnsbit** [comment]
New build fixes all .iso I have tested and it seems most .cue/.bin combos.  The Secret of Monkey Island is still bombing.  I tested a few CD's with underscores to rule that out and they work.  I am attaching a new video showing it and also the .cue sheet for monkey island to see if that helps you.
[2021-07-01 15-03-03.zip](https://github.com/MiSTer-devel/ao486_MiSTer/files/6750530/2021-07-01.15-03-03.zip)
[the_sec.zip](https://github.com/MiSTer-devel/ao486_MiSTer/files/6750531/the_sec.zip)

**Comment by flynnsbit** [comment]
Nevermind, new build works as expected. I had a script error on my side with those two games.  I will keep testing but I think I am good.

**Comment by flynnsbit** [comment]
All good here @sorgelig.  Everything is working now.  I am closing the ticket.  Thank you again for the fix and all you do.
