### ISSUE TITLE
MT32-PI menu no longer appearing

### ISSUE THREAD

**Issue by mitchelln** [MiSTer-devel/ao486_MiSTer#74]
The MT32-PI menu is no longer showing in the config menu. MIDI sound is working as expected though, so it is communicating with the MT32-PI.

**Comment by sorgelig** [comment]
it works for me. So it must be something else in your config. May be USB connector is not fully connected. MIDI output can work in blind mode, so non-MT32pi device (like real MIDI synth) can also get MIDI output.
So this is your case. MT32pi communication (i2c) it seems not working by unknown reason, so MT32pi works as a generic MIDI synth.

**Comment by mitchelln** [comment]
It's definitely playing via the MT32-PI as when I change the Synth mode or Soundfont ROM via the buttons, the output changes as expected. The menu just suddenly stopped working, I assumed after a recent update.
Will on older RBF still work with the latest MiSTer Main to test?
Thanks.
________________________________

**Comment by sorgelig** [comment]
I think you can mix previous and current versions of both ao486 and Main. i don't remember any viable change in Main against ao486 in recent update.

**Comment by mitchelln** [comment]
Thanks. I'll give that a go just in case. A bit baffled as to what has changed in my setup, so this will help narrow it down.
________________________________

**Comment by mitchelln** [comment]
No, fails with an ATA device detection failure with older RBF. Time to break out the oscilloscope...
________________________________

**Comment by sorgelig** [comment]
even with failure of ATA, MT32 menu should work.
you can downgrade both Main and ao486 as well

**Comment by mitchelln** [comment]
I tried another Raspberry Pi and it works. So it looks like my Pi 3A+ has failed, which is worrying. It almost looks tristate on the oscilloscope. Anyway, nothing to do with the core.
Thanks for your help with this.
________________________________

**Comment by sorgelig** [comment]
make sure RPi gets enough power. It's especially tricky through USB cable.
