### ISSUE TITLE
PS/2 mouse support looks broken

### ISSUE THREAD

**Issue by p2mate** [MiSTer-devel/ao486_MiSTer#77]
[mouse.zip](https://github.com/MiSTer-devel/ao486_MiSTer/files/7110308/mouse.zip)
contains a simple test program which uses the ps/2 hw directly. If you start the program and carefully move the mouse or press a button, things work. But at some point it seems a byte gets lost and the program misinterprets the byte stream coming from the mouse. Similar behaviour is seen with cutemouse and win95.

**Comment by sorgelig** [comment]
after using your util mouse got broken.
But if i don't use this util, then everything works fine. 
I use CuteMouse v1.9.1
Windows 95/98 also have no problem - make sure you don't load any mouse driver while loading windows.

**Comment by p2mate** [comment]
I tried with both cutemouse 1.91 and 2.1 beta 4, not using the test program. If you use the test program, cutemouse needs to be unloaded first I think because it talks to the hw directly rather than using the BIOS interface like cutemouse does. My guess is it might have to do with the number of events the mouse generates. However other cores (eg Archie, AtariST or Minimig) work fine while they use the same communication mechanism between the MiSTer binary and the FPGA core if I get it right.

**Comment by p2mate** [comment]
Using a logitech G305 mouse by the way.

**Comment by p2mate** [comment]
a Dell branded logitech mouse seems to work (USB vendor ID 046a, product ID 010d)

**Comment by sorgelig** [comment]
You are communicating with i8042 chip in the core. Application inside ao486 never talks directly to mouse or keyboard. MiSTer only supports simple mouse communication implemented in BIOS. Other modes aren't implemented. Only option really can be used is disable/enable mouse/keyboard. Other options outside of i8042 state aren't implemented. Original PS2 mouse (and keyboard) have some commands which can be sent from PC - all replies are faked to app by Main (MiSTer binary) and never go to real mouse. 
I remember mouse have 2 modes - one is using interrupt mode after which mouse data should be read. This mode is implemented and should be used. Other mode is query of mouse for data - this mode is not implemented. Only interrupt mode guaranteed data alignment, so using interrupt is mandatory for mouse.
Since 99.9% DOS and Windows apps relay on mouse driver, a proper drive choice fixes all mouse problems.

If you really want, then you are welcome to improve PS/2 communication in core or Main

**Comment by sorgelig** [comment]
Probably, using high-DPI mouse will flood the core with data, so it may loose the data..
try ```mouse_throttle``` option in MiSTer.ini 



> However other cores (eg Archie, AtariST or Minimig) work fine while they use the same communication mechanism between the MiSTer binary and the FPGA core if I get it right.

but inside cores implementations are different due to different original HW.

**Comment by p2mate** [comment]
> You are communicating with i8042 chip in the core. Application inside ao486 never talks directly to mouse or keyboard. MiSTer only supports simple mouse communication implemented in BIOS. Other modes aren't implemented. Only option really can be used is disable/enable mouse/keyboard. Other options outside of i8042 state aren't implemented. Original PS2 mouse (and keyboard) have some commands which can be sent from PC - all replies are faked to app by Main (MiSTer binary) and never go to real mouse.

Yes, this is intentional to rule out a BIOS bug. In general the program uses the streaming mode just like the BIOS does, however it does not use the IRQ but just polls the i8042 instead.

> I remember mouse have 2 modes - one is using interrupt mode after which mouse data should be read. This mode is implemented and should be used. Other mode is query of mouse for data - this mode is not implemented (at least never tested). Only interrupt mode guaranteed data alignment, so using interrupt is mandatory for mouse.
> Since 99.9% DOS and Windows apps relay on mouse driver, a proper drive choice fixes all mouse problems.
> 
> If you really want, then you are welcome to improve PS/2 communication in core or Main

I'm guessing the core is overrun because I would be surprised the CPU can't keep up with the datastream. So the solution could be to reduce the report rate on 'fast' mice or obviously use a more normal mouse.

**Comment by sorgelig** [comment]
Probably mouse reports can be combined by summing X/Y offsets, but it's unclear how to make it effectively. Before it used accumulator added by input devices and pushed to the core at some intervals. While it may help in some cores like overrun on ao486, it may introduce unneeded input lag in other more time sensitive scenarios. 
Probably accumulating should be done on core side according to specific needs.

**Comment by p2mate** [comment]
My plan was actually to send a command to the mouse to reduce the reporting rate if the main binary notices the AO486 core is active. I haven't quite figured out how to do that though and ofcourse what to do if there are multiple USB mice connected.. Another approach could be to use a parallel interface between hps_io and the core. Not sure how difficult this would be though.

**Comment by sorgelig** [comment]
I suggest to use either mouse with lower DPI or advanced one which has option to switch DPI by buttons.
It's easier to solve by choosing a right mouse.

**Comment by p2mate** [comment]
The G305 allows changing the DPI however it doesn't help. I think the problem is the report rate which is also configurable on windows. Default is 1kHz which is higher than the maximum of 200Hz the PS/2 protocol seems to support according to https://wiki.osdev.org/PS/2_Mouse. https://en.wikipedia.org/wiki/PS/2_port suggests the default report rate of PS/2 mice is 100Hz, so the G305 would default to a 10x higher rate. Also the default rate for USB mice is 125Hz which is probably still low enough to not overrun the i8042. I haven't found a way to set the report rate on linux.

**Comment by sorgelig** [comment]
i don't understand why i have no problems with mouse (if i don't use your app).

**Comment by p2mate** [comment]
Some more data:
(Logitech G402)

[    5.521528] HID usage: 0x00010006, original interval: 1
[    5.521550] HID usage: 0x00010006, applied interval: 1
[    5.574889] hid-generic 0003:046D:C07E.0004: input,hiddev0,hidraw3: USB HID v1.11 Keyboard [Logitech Gaming Mouse G402] on usb-ffb40000.usb-1.3.3/input1

does not work

(Dell branded logitech mouse)
[  973.752239] HID usage: 0x00010002, original interval: 10
[  973.752276] HID usage: 0x00010002, applied interval: 10
[  973.805902] hid-generic 0003:046D:C016.0005: input,hidraw2: USB HID v1.10 Mouse [Logitech Optical USB Mouse] on usb-ffb40000.usb-1.3.3/input0

notice the difference in polling intervals. This interval actually comes from the mouse USB data (see below, lvl indicates the polling interval as reported by the mouse). It is possible to override but only using a module parameter.  (see https://github.com/MiSTer-devel/Linux-Kernel_MiSTer/blob/bbeff2c30ba10cb74a084566c1e3dc8976f6a8e0/drivers/hid/usbhid/hid-core.c#L1118 and following lines)

Logitech G402 descriptor:

T:  Bus=03 Lev=02 Prnt=02 Port=06 Cnt=03 Dev#=  8 Spd=12   MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=046d ProdID=c07e Rev=90.02
S:  Manufacturer=Logitech
S:  Product=Gaming Mouse G402
S:  SerialNumber=6D80267D4854
C:* #Ifs= 2 Cfg#= 1 Atr=a0 MxPwr=300mA
I:* If#= 0 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=01 Prot=02 Driver=usbhid
E:  Ad=81(I) Atr=03(Int.) MxPS=   8 Ivl=1ms
I:* If#= 1 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid
E:  Ad=82(I) Atr=03(Int.) MxPS=  20 Ivl=1ms

Dell branded logitech mouse descriptor:

T:  Bus=03 Lev=03 Prnt=04 Port=02 Cnt=02 Dev#=  7 Spd=1.5  MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS= 8 #Cfgs=  1
P:  Vendor=046d ProdID=c016 Rev= 3.40
S:  Manufacturer=Logitech
S:  Product=Optical USB Mouse
C:* #Ifs= 1 Cfg#= 1 Atr=a0 MxPwr=100mA
I:* If#= 0 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=01 Prot=02 Driver=usbhid
E:  Ad=81(I) Atr=03(Int.) MxPS=   4 Ivl=10ms

**Comment by p2mate** [comment]
/media/fat/linux# cat u-boot.txt
v=usbhid.mousepoll=10

makes also the G402 and G305 work by forcing the poll interval to 10ms

**Comment by iso70x** [comment]
I tried the AO486 core for the first time in a while today (last time being before the the recent linux updates), and have experienced this issue also.  I don't have any technical info to add, but just confirming everything reported by p2mate is also hitting other logitech mice, and that this mouse was definitely working with AO486 previously.  I have a Logitech G903, so guessing it's all of their gaming mice that are causing this problem.  I get the same result whether it's using the wireless dongle or connected directly via USB cable to the MiSTer.  Switching report rate via the u-boot.txt file allows the mouse to function with the AO486 core.  All other cores supporting mouse input seem fine at default 1ms rate.  I have other mice that are still working fine.

**Comment by sorgelig** [comment]
i've added some pace control for mouse messages.
Please try this build of Main:
[MiSTer.zip](https://github.com/MiSTer-devel/ao486_MiSTer/files/7171897/MiSTer.zip)

**Comment by p2mate** [comment]
it works fine. thanks!

**Comment by sorgelig** [comment]
this is better version. It sends mouse buttons state immediately, so should be better for time sensitive cases:
[MiSTer2.zip](https://github.com/MiSTer-devel/ao486_MiSTer/files/7172511/MiSTer2.zip)
please try it.

**Comment by p2mate** [comment]
also works fine.

**Comment by M-Walrus** [comment]
I also have this issue in the AO486 core with my mouse after updating to the new linux yesterday.
It seemed like the mouse was sending other commands to the core besides just x/y.  This same mouse worked for the past 2 years on MiSTer without issues. Logitech g400s

The build @sorgelig posted above "MiSTer2.zip" fixed it for me.  Thanks!
