### ISSUE TITLE
OSD Horizontal and vertical position control in ao486 Core

### ISSUE THREAD

**Issue by lencio** [MiSTer-devel/ao486_MiSTer#83]
I have a problem with the position of the image on the screen of the ao486 core in several CRT televisions (15hz), using VGA / SCART.
Basically the problem is that on some TVs, the core is off-center to the left, even losing the entire edge.
On other TVs, the core is off-center to the right, or above the screen, losing the upper edge depending on the model.
It is an issue that I have reported in Main_MiSTer and I have been answered (thank you) that it is better to post the problem in each core individually, since it is not possible to implement it at the framework level.
It would be great to have a Horizontal / Vertical position control in the OSD to be able to center the image regardless of the TV used.
I have tested the real machine on different TVs and curiously the image does come out perfectly centered.
I have tried several SONY trinitrons as well, such as SAMSUNG and SANYO models.

**Comment by sorgelig** [comment]
ao486 core has to use vga_scaler=1 mode. So position is fully depends on HDMI video mode you use. You can define custom video mode to suit your TV.

**Comment by lencio** [comment]
Closure at the request of @tacertain
