### ISSUE TITLE
Move folders bios and drv from /releases to another folder

### ISSUE THREAD

**Issue by theypsilon** [MiSTer-devel/ao486_MiSTer#87]
Since bios and drv folders are not meant to be distributed in AO486 games folder, they better should go in another directory.

![imagen](https://user-images.githubusercontent.com/852246/149209785-c0a8b722-cadf-4095-b93d-82404c23d070.png)

**Comment by sorgelig** [comment]
moved BIOSes. drv subfolder has no better place to put, so leave it as is.
