### ISSUE TITLE
EMM386 incompatibility due a "enable CD-ROM boot" feature

### ISSUE THREAD

**Issue by spark2k06** [MiSTer-devel/ao486_MiSTer#92]
There is something in this new feature (https://github.com/MiSTer-devel/ao486_MiSTer/commit/03375e6edf7986ca6a6b5d63c21c7926b5dc7657) causes the following entry in CONFIG.SYS to not work:

`DEVICEHIGH=C:\DOS\EMM386.EXE NOEMS HIGHSCAN I=B000-B7FF 4500 FRAME=E000 d=256`

When loading this driver with these parameters, it hangs. The previous boot0.rom file works without problems.

**Comment by sorgelig** [comment]
BIOS obviously includes additional code to handle boot which changes a little BIOS system memory. It doesn't mean there is a bug. It only means you need to find other working parameters for EMM386.

**Comment by spark2k06** [comment]
I took that possibility into account, and also tried changing the controller address to D000, instead of B000, same effect. I didn't seem to see the code in the E000 window either... I'll check the BIOS code well to see where that boot code you mentioned is located.

**Comment by spark2k06** [comment]
Ok. It seems that the problem is in the HIGHSCAN argument:

http://info.wsisiz.edu.pl/~bse26236/batutil/help/EMM386S.HTM

HIGHSCAN
    Specifies that EMM386 use an additional check to determine the
    availablity of upper memory for use as UMBs or EMS windows. On some
    computers, specifying this switch may have no effect or cause EMM386 to
    identify upper memory areas as available when they are not. As a
    result, your computer might stop responding.

I close the issue.
