### ISSUE TITLE
Black screen with the latest boot0.rom

### ISSUE THREAD

**Issue by solskogen** [MiSTer-devel/ao486_MiSTer#98]
I only get a black screen with the latest boot0.rom

**Comment by NML32** [comment]
Same here.

**Comment by sorgelig** [comment]
it's not a real issue. It just needs to compile both rbf and main from latest sources. I will update it soon.

**Comment by solskogen** [comment]
It's a bit of a issue, since the downloader.sh downloads the latest bios :-)

**Comment by solskogen** [comment]
Now it works!
