### ISSUE TITLE
Corrupted colors

### ISSUE THREAD

**Issue by kiFlaFlaki** [MiSTer-devel/ao486_MiSTer#99]
ao486_20220224.rbf, latest boot.rom and boot1.rom files, latest Main (v220224):
Corrupted colors (Star Wars: Dark Forces, The Secret of Monkey Island, Syndicate, Tyrian 2000...)

**Comment by Rumbledethumps** [comment]
I found the same problem upgrading from 20220211 to 20220224. Anything using graphics mode. Also, the system was unstable. I tracked this down to the "VSync" setting. "60Hz" works fine but "Variable" is corrupt and unstable; reset the core after changing the setting.

**Comment by flynnsbit** [comment]
@decod81 Any insights here?

**Comment by decod81** [comment]
> @decod81 Any insights here?

The new rbf that is now in the official repository doesn't seem to work for me so obviously it's different from my version somehow. I guess there was also some other patch applied and I guess the rom was updated as well.

You can test my version if you like here (use the previous rom): https://github.com/decod81/ao486_MiSTer/blob/master/releases/ao486.rbf. 

I haven't experienced any instability, but I did notice that sometimes colors get mixed with the 70 Hz setting. Disabling L2 cache seems to eliminate this issue so I'm guessing it has something to do with cache coherence. You can switch L2 cache back on after the video mode has changed if you need the speed and the games keep working ok. So based on that I presume it has something to do with setting the palette at unsuitable time respect to some cache operation.

**Comment by virtualisoftware** [comment]
Yes, same issue here, colors are garbled on screen, unless vsync adjust is disabled in Mister.INI

[ao486]
vsync_adjust = 0

**Comment by sorgelig** [comment]
this commit:
https://github.com/MiSTer-devel/ao486_MiSTer/commit/f524b4ffb48a11bd2005de2e489ce258607b5095
broke colors

**Comment by flynnsbit** [comment]
Hopefully this can be rolled forward with a fix for the colors instead of rolled back to the jittery video that happened in a lot of great games. (Commander Keen, Jazz Jackrabbit, etc)  This was a big issue for years that made some really great games hard to play on the core.

**Comment by sorgelig** [comment]
I'm compiling release. This commit will be reverted. If there will be correct fix, then it will be of course added.

**Comment by mills32** [comment]
I remember having some issues on a real PC in a game called Lychnis, and some demos I was programming. Hardware scroll can disable custom palettes on "SVGA" cards if the pel panning register (3C0 index 13) takes values that are not 0, 2, 4 or 6. Maybe this has something to do with that. I'm going to test that game and a little program to see if it is related.

**Comment by kiFlaFlaki** [comment]
New release fixed corrupted colors. Thanks!

**Comment by decod81** [comment]
I made a further fix that  seems to fix the colors and the scrolling bug simultaneously now. Here's a precompiled version of the fix:

https://github.com/decod81/ao486_MiSTer/blob/master/releases/ao486_vgafix2.rbf

I tested this now with 10 starts of wolf3d, prince of persia, monkey island, dark forces, supaplex and keen4 and I didn't observe any color or scrolling issues so far, but you never know so before I submit the patch, I'd like to hear from other people that it works for you as well?

**Comment by kiFlaFlaki** [comment]
I tried some problematic games (Jazz JackRabbit, Monkey Island, Wing Commander, Commander Keen (miltiple starting each game)  and I can confirm that I didn't see any color corruption. Scrolling is great now. Anyway, that was 30 min testing period.

**Comment by mills32** [comment]
I tested this vgafix core, and it seems to fix the colors bug. Scroll is still pefect :). The colors bug on the bugged version, shows if you reload the core from the core menu itself, I did the same with this new core and it worked well.

**Comment by decod81** [comment]
Sounds like it works then so I'll make another pull request for this fix.

**Comment by flynnsbit** [comment]
Working well, I can't break it.

**Comment by wwark** [comment]
thank you for the last fix !

**Comment by jsmolina** [comment]
Lot of thanks!!  that VGA scroll issue was disturbing
